cache: packages
sudo: required
warnings_are_errors: false
services:
  - docker
#language: python
# # We shall remove them since we shall only test with 3. 
# # No future support for Python2.7 
# # python:
# #   - "2.7" 
#    - "3.5"


# database setup
before_install:
-  docker-compose ps

# command to run tests using py.test
script:
-  docker-compose  run --service-ports python_retriever py.test -v --cov=retriever  || exit 1

after_success:
  - codecov

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
