sudo: false
language: python
python:
  - "2.7"
  - "3.5"
addons:
  postgresql: "9.4"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov -U
  - pip install pytest-cov -U
  - pip install pytest-xdist -U


# command to run tests using py.test

script:
  - py.test -v --cov=retriever

# database setup
before_script:
  - sqlite3 --version
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database testdb;' -U postgres

after_success:
  - codecov


after_script:
  - pip install retriever -I
  - retriever -v
  - retriever ls
  - py.test test/test_backward_compatibility.py -v

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
